export const DEFAULT_INCLUDED = [
  { id: "premio_mensal", label: "Prêmio Mensal", description: "Valor da mensalidade do seguro conforme plano contratado." },
  { id: "app_morte", label: "APP – Morte / Invalidez R$ 10.000,00", description: "Cobertura exclusiva para motociclistas em caso de morte ou invalidez decorrente de acidente pessoal." },
  { id: "colisao", label: "Colisão, Perda Total, Perda Parcial, Incêndio e Fenômenos da Natureza", description: "Cobre danos ao veículo por colisão, perda total ou parcial, incêndio, raio, explosão e fenômenos da natureza como enchentes e granizo." },
  { id: "rcf_materiais_100", label: "RCF – Danos Materiais R$ 100.000,00", description: "Responsabilidade Civil Facultativa para danos materiais causados a terceiros em acidentes, com cobertura de até R$ 100.000,00." },
  { id: "carro_reserva_7", label: "Carro Reserva 7 Dias", description: "Disponibiliza um veículo reserva por até 7 dias, com liberação somente após sinistro por colisão." },
  { id: "auxilio_retorno", label: "Auxílio Retorno Domiciliar – R$ 200,00", description: "Reembolso de até R$ 200,00 para despesas de retorno ao domicílio após sinistro." },
  { id: "guincho_sinistro", label: "Guincho Ilimitado (Colisão até oficina)", description: "Guincho ilimitado em caso de sinistro por colisão, até a oficina credenciada mais próxima." },
  { id: "assistencia_500", label: "Assistência 24 Horas 500 km", description: "Assistência 24h com cobertura de 500 km (250 km ida + 250 km volta), incluindo reboque, pane seca, chaveiro e outros serviços." },
  { id: "rcf_corporais_100", label: "RCF – Danos Corporais R$ 100.000,00", description: "Responsabilidade Civil Facultativa para danos corporais causados a terceiros, com cobertura de até R$ 100.000,00." },
  { id: "seguro_vida", label: "Seguro de Vida (Morte Natural/Acidental) – R$ 10.000,00", description: "Cobertura de seguro de vida para o segurado em caso de morte natural ou acidental, no valor de R$ 10.000,00." },
  { id: "vistoria", label: "Vistoria Padrão – Auto", description: "Vistoria veicular padrão para habilitação do seguro." },
  { id: "roubo_furto", label: "Roubo e Furto", description: "Cobertura total em caso de roubo ou furto do veículo, com indenização conforme valor FIPE na data do sinistro." },
];

export const OPTIONAL_COVERAGES = [
  { id: "rastreador_go", label: "Rastreador GO", description: "Instalação de rastreador veicular para monitoramento em tempo real." },
  { id: "carro_reserva_30", label: "Carro Reserva 30 Dias", description: "Veículo reserva por até 30 dias após sinistro por colisão." },
  { id: "assistencia_residencial", label: "Assistência Residencial", description: "Serviços de assistência para sua residência: encanador, eletricista, chaveiro e outros." },
  { id: "auxilio_funeral", label: "Auxílio Funeral", description: "Cobertura para despesas funerárias do segurado e familiares diretos." },
  { id: "carro_reserva_15", label: "Carro Reserva 15 Dias", description: "Veículo reserva por até 15 dias após sinistro por colisão." },
  { id: "assistencia_1000", label: "Assistência 24 Horas 1.000 km", description: "Assistência 24h ampliada de 1.000 km (500 km ida + 500 km volta)." },
  { id: "vidros_40", label: "Vidros, Para-brisa e Franquia 40%", description: "Cobertura para vidros e para-brisa com franquia de 40% do valor do reparo." },
  { id: "taxa_go", label: "Taxa de Instalação GO", description: "Taxa de instalação do rastreador GO." },
  { id: "vidros_completo_40", label: "Vidros, Faróis, Retrovisores, Para-brisa e Lanternas – Franquia 40%", description: "Cobertura ampliada para vidros, faróis, retrovisores, para-brisa e lanternas com franquia de 40%." },
  { id: "rcf_materiais_150", label: "RCF – Danos Materiais até R$ 150.000,00", description: "Ampliação da Responsabilidade Civil para danos materiais a terceiros com limite de R$ 150.000,00." },
  { id: "rcf_corporais_150", label: "RCF – Danos Corporais até R$ 150.000,00", description: "Ampliação da Responsabilidade Civil para danos corporais a terceiros com limite de R$ 150.000,00." },
  { id: "app_invalidez_55", label: "APP – Invalidez Permanente Total ou Parcial R$ 55.000,00", description: "Cobertura de R$ 55.000,00 em caso de invalidez permanente total ou parcial por acidente pessoal." },
  { id: "app_morte_10", label: "APP – Morte / Invalidez R$ 10.000,00", description: "Cobertura adicional de R$ 10.000,00 por morte ou invalidez em acidente pessoal." },
  { id: "rcf_morais_10", label: "RCF – Danos Morais R$ 10.000,00", description: "Cobertura para danos morais causados a terceiros com limite de R$ 10.000,00." },
  { id: "rcf_morais_20", label: "RCF – Danos Morais R$ 20.000,00", description: "Cobertura ampliada para danos morais causados a terceiros com limite de R$ 20.000,00." },
  { id: "monitoramento", label: "Monitoramento Veicular", description: "Serviço de monitoramento contínuo do veículo por central especializada." },
  { id: "casco_50", label: "Cobertura Máxima do Casco R$ 50.000,00", description: "Cobertura máxima do casco limitada a R$ 50.000,00 independente do valor FIPE." },
];
